site:
  name: DurianPy
  site: 'https://astrowind.vercel.app'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Pycon Mini Davao
    template: '%s — Pycon Mini Davao'
  description: 'PyConf Mini Davao is a half-day afternoon event dedicated to expanding and strengthening the Python community in Davao City under the theme "Empowering Innovation Through Python." The event will feature three keynote speakers and a series of lightning talks focused on exploring how Python technologies are driving innovation across local tech startups and agencies. Our goal is to foster a collaborative environment that provides a platform for knowledge-sharing, community-building, and the growth of Python enthusiasts, especially beginners.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Pycon Mini Davao
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
